replicaCount: 2

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

tls:
  enabled: true
  secretName: podinfo-tls-secret

ui:
  color: "###ZARF_VAR_PODINFO_TOO_UI_COLOR###"
