---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: podinfo
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: podinfo-too
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDRENDQW5DZ0F3SUJBZ0lSQUw2YUtpWnM3TjVHZEhvNXZMWld4SHN3RFFZSktvWklodmNOQVFFTEJRQXcKVVRFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNUk13RVFZRFZRUUxEQXB5YjI5MApRRzF3Wlc1Mk1Sb3dHQVlEVlFRRERCRnRhMk5sY25RZ2NtOXZkRUJ0Y0dWdWRqQWVGdzB5TXpBMU1URXhOelUyCk1EaGFGdzB5TlRBNE1URXhOelUyTURoYU1ENHhKekFsQmdOVkJBb1RIbTFyWTJWeWRDQmtaWFpsYkc5d2JXVnUKZENCalpYSjBhV1pwWTJGMFpURVRNQkVHQTFVRUN3d0tjbTl2ZEVCdGNHVnVkakNDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3JCUGZEbnBQaGpFQWZ1VDM4cjN2SjhyMGtVdkNDY3dpN3NVODV4CjFENmxxWE9kSDkvNFJVODJGUGlaaWRLU2JudkdVaDl4RVVuQVhxbHp0d2o2eHR0d0hNOVEvRGxRYkNQZHFxTU8KRlhjZFcrSGlqNFBKQ0tZUCtvOVAwOGdwbk1sZGh2OWl5L1N2QjR0Ly9tRUg3VFF1elZ3R3A1OFBwdyttMHFETgpERTliaW04QVI0L0ZnWS9PcWQ2TSt4MFg1R2hzWStDTFpMdnhVUXJqWXJ5RldTek9ydis3SCtnb25lcEJWV01VCnhKNlFZeGt1TXd6MXh4Wk1WNmpzeW02SjdhMGNaVlg5elZHeGhqOXEvVjVYdmpJRnBUZzIxMStDK2hhbE1VeDkKNDdJZFpsQmxaTmpRcXUxZnNNd0lTOWZjdXIrbHF2aU1pSjk1Q0JxdnV2dEYwZjhDQXdFQUFhTnVNR3d3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1COEdBMVVkSXdRWU1CYUFGRmRiCmdEYVhUS3ZJMG11dG1YcWpxV2FqQWpVVU1DUUdBMVVkRVFRZE1CdUNHU291Y0dGemMzUm9jbTkxWjJndVltbG4KWW1GdVp5NWtaWFl3RFFZSktvWklodmNOQVFFTEJRQURnZ0dCQUFMaWtXM2lYalV6dTVBVmk0UmwwcU5XcTBoYgpGRGtqZjhTbTdLc05vRXNWSkV0Zko2eFIzTC84UGlEd05yZ2h3OWZTUDVyc21YTUpDdU1qQ2J1MmErV1A3anVvCll3NjRjQjdwME5nVW9pV1IvbzdnS1hIcWF1Z0w2OGYyS3JQR0VlMXFDb1VzMklLZHdHTkMyYTdzeEtFYmNyZk0KQWEvTDE2VldSeUNLcFBUdjBMY0VpTnVRa0ZVYWdzWCttMjlPYjBtTGovTHRUMkZCYWppTVp5a0tIbnR6ZnBVVwpXR2dSK05EdW1VUDlVUlVLeEhtLzIyVXlZbkJRSUMrcE1CMHI0alFlN1FNOGVtMFVkUXVka1FWVlI1SU8rckQ0CjQ3RnhFTkNkVk5HUVlranRQQ3RsYzJnM0RkUVFZU3FjMWcxaUlEM1VlOHd0Tm1vWmlUclpJc3Y0cFJhNHRCRUsKWjErWDdiVHlDZEx0MktMdktEbDZTT1VLL2lEdHRhQzZIQkRDM3IrL0g3NkMvbWZTNkgrU1NXU2VPVU5sT3FaUwpMRGlzckU2T3ZjN1dBZnpJRmlZdW9YSUxiYTUzVWtJcDZQMmNVSHpGYzFsaWVpWGVaQzl4ZDlYb2V1cVpvbEZLCkRDQm1lSWRBSk5Ua1A1UFdvY0JyMnU3eVJQRm0zZVBaWmJmeGhnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3F3VDN3NTZUNFl4QUgKN2s5L0s5N3lmSzlKRkx3Z25NSXU3RlBPY2RRK3BhbHpuUi9mK0VWUE5oVDRtWW5Ta201N3hsSWZjUkZKd0Y2cApjN2NJK3NiYmNCelBVUHc1VUd3ajNhcWpEaFYzSFZ2aDRvK0R5UWltRC9xUFQ5UElLWnpKWFliL1lzdjByd2VMCmYvNWhCKzAwTHMxY0JxZWZENmNQcHRLZ3pReFBXNHB2QUVlUHhZR1B6cW5lalBzZEYrUm9iR1BnaTJTNzhWRUsKNDJLOGhWa3N6cTcvdXgvb0tKM3FRVlZqRk1TZWtHTVpMak1NOWNjV1RGZW83TXB1aWUydEhHVlYvYzFSc1lZLwphdjFlVjc0eUJhVTROdGRmZ3ZvV3BURk1mZU95SFdaUVpXVFkwS3J0WDdETUNFdlgzTHEvcGFyNGpJaWZlUWdhCnI3cjdSZEgvQWdNQkFBRUNnZ0VBQUlvUnR3UVVTbENOeVdpZ1NhZUswYnRCRm5zQlNSMFZvKzVOS1hiRWs5b1UKR2ZCaUhHUDlYQTJ3clVSVzRocGlUUFBJYUo4RHpmYlVsYlp1MnBGb05XTTZSQkZlYXBQdGM0T011VzBlOWp4YQpnUEVsUU9aT3A2K2ZPL3Fsa1psSURIN0dJV0pmZ0l0WSs4RFF2ZCszaVJXb3dtU20vT0tneFhUaWIyMldYMTNLClZOTDJPUUVyOFRIVHRYQ2VReEhKZDU3ZEEwV21RVHR3UVloNThWeER3dEpLbUZ6TkRPdmRvSWFMYzEzdmhPV2UKRXBPZkZSNzJRcUFhWUlUN3hCV3JvbDdaSGJXamxRM0tHc3hZaDB5OCtndC9QOFFKaUVPRTBCSjVaQUI1V3pUbwpzNjBva1M1bDlBTFRiZzN4SlNtUS85ZGFpMGxkb2lOc1hGRjE4VkFMbVFLQmdRRFlmVXVUZnNNSlNPa09mNGd6CnNKOTR4a2EwTlJtalF5RVV1cUE3Mi9Xd3dMTG1ocGswc3ZkbzB1SHJobG5rYWkvL3dsSHdqelNwTkJKcWFjOHYKTzQ2ZFBlbzVpVjhVZDFWcFpQRzk4ejlta3ROeU8zKys4dmJNR2ZMZTRuSXl6TW9TRFA5dkhtN0lVejYwM0VJeQpEcjZQZEl0a3gwWmdtbFM5UDFjS0M0b21Zd0tCZ1FESjZ5amxrNTBnQkdaWVFpdDhYczVUb2IwRTFla1F4S0hmCm1GS2ovTCs5VndVQnlrUUpPM3E3YU1pUVQwUkt4T2M2U2FLT1A5MFcrVVpLZDQ4SDhpSC8vMHVLVmpMRVhQM3QKSWFWZGlhN2hLbHZpUnBCamZjeGs2STNpaFd1MlBNM2dobHFIUFlSWTBnM2pXYXZpQVNCeFNERkxsWTg0dGV3Rgo2NlVMZnpUNnRRS0JnRG00Qml0WDg2WUpFMkh6TEp3amJoRWtRL3VONEx6L2k5VmNBSmFWQ1lkTGlTY2ZJYi9FCksyUitQUSt2YlU0UjVhUTU2ZURLUFk4VFBBbTFGakVRbnZCYmJwUlNoTkFQRk8yWnBUNHdtV20rb2JObUc2UU0KWVRKL2hKcGFJM3BaMFZKSXR0Mm9ibjdvZXVKN2l3YVBtY3pqbExxVXlyVzh6L1Q0NnpyWllzYmpBb0dBY25sYQoxMFVuNkhYMkhBVnZwL1FMMzRncnBHa3QyQzdTWXZSMXJiam1iNDY5TFBXaU91VzR3RFU0dCsvb2xNY3JISFdRCnJqcnd1a3lhbUM5T0xNQU9uSmI5R2JHaTJJYXNBMXQyNkIvZHdKUUdRYk9sdW5JZ2hmaitMN1ZhaXBmUVZJRjMKSTRNeDNEVkNZR2wvTkFOVmhFUGNockNFNFM3cVg3VG4vaXVoT3AwQ2dZQXpPZWwxNDhVZDE4OFpnVllRai9EeApRc3FadUpvQXZ2ZzI5WnRYQXh3OGFmWUlod1U4UW9DVVo5cVB1dGsydnA3NWRBeTVwd0RvVjA2ajRBbmhnUjlNCitJNi94eHhVSU1UdFdMamlXZmVPZGFEcS81cVBuMit2VkNnTkRLNG5VU2IxWjBsQ0kvYk9ZYzlmYWtkUVNqNVkKcEY0akdnN0FaSEF2NjhMelk5U1FBdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: null
  name: podinfo-tls-secret
  namespace: podinfo-too
type: kubernetes.io/tls
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: podinfo
  namespace: podinfo
spec:
  gateways:
  - istio-system/public
  hosts:
  - podinfo.bigbang.dev
  http:
  - route:
    - destination:
        host: podinfo
        port:
          number: 9898
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: podinfo-too
  namespace: podinfo-too
spec:
  gateways:
  - istio-system/passthrough
  hosts:
  - keycloak.bigbang.dev
  tls:
  - match:
    - sniHosts: ["keycloak.bigbang.dev"]
    route:
    - destination:
        host: podinfo-too
        port:
          number: 9899
---
