---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: podinfo
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: podinfo-too
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVLakNDQXBLZ0F3SUJBZ0lSQUpDZVJlTlRYckErTWd1S1p2MHFla3N3RFFZSktvWklodmNOQVFFTEJRQXcKYXpFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU0F3SGdZRFZRUUxEQmR3WVd4aApjM05wYzBCd1lXeGhjM05wY3kxeVlYcGxjakVuTUNVR0ExVUVBd3dlYld0alpYSjBJSEJoYkdGemMybHpRSEJoCmJHRnpjMmx6TFhKaGVtVnlNQjRYRFRJek1EVXhNakUwTkRneU1Gb1hEVEkxTURneE1qRTBORGd5TUZvd1N6RW4KTUNVR0ExVUVDaE1lYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUdObGNuUnBabWxqWVhSbE1TQXdIZ1lEVlFRTApEQmR3WVd4aGMzTnBjMEJ3WVd4aGMzTnBjeTF5WVhwbGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFMNHArOVRjN2d6VEJBd0FUUFZBNWorbUlpYkVHeW1uelpSN2JXMTI2MXlSRHM3ZXJ0ZGwKZFNLUWptSnp3cld5Yitrd2pUelcrVTN5WjJvRTBBdXZJMmxrUk83NlVSc29UMVNiWTZBL1dEU1FLTVZENFNlYgpUYzlKbFp4UlJTVkZ3TkNGL1hicDRveE1Wbk1CL1hBRVF3WjcvTVZzb1RVYms4RFJPdWJFWEJlTSs3ZHFiZHpGCk9lajY0UjVJZ0hSakVBbWxqOG9sQWR1RElSbjcwS3ZjMEtBbFJzWTJYSVNSbS92UHkwMU5Ha3ZkZjZXc0t6L28KWERDVkMzaC9FOEhVY0xaYnJYSnp5bnFpRlpkcHptMUlNeEZUeStzb1ZhbGpOYXFCMVo0SkxBQmtyT2ViZFIzRQp0blRsZ1VVc0YyVjVaNWxkdmNpdzYyZDdNTjA4RU9lbzBqa0NBd0VBQWFOcE1HY3dEZ1lEVlIwUEFRSC9CQVFECkFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUI4R0ExVWRJd1FZTUJhQUZEK1FZVTREYUNobTRBWGYKaUFrb1g1V1NBWWYwTUI4R0ExVWRFUVFZTUJhQ0ZHdGxlV05zYjJGckxtSnBaMkpoYm1jdVpHVjJNQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCZ1FDaENWL0NVcGpjQzBvb2gza3B0cWpKeUFjZ1FLbmJsNFF1TXk4ekoycnVMcWx4CmtZYzBqNFd1cnd0MGZsZFlEcUo0Z1czRU1KWmdpY2E2QlVBcHJUQnpqdy9BMHpUYXhIWUJNYytRNWhuekJOcmUKcXlWMENMVXlKdVlPd3pLRHhpbGpjYnlqb2szUTljbVFsVkxKNU5IQnVtZEJQNkd1TVg2OHNWWFduaEVhTTQ3OQpGbkVSSzBSREx1SWxXaFNOaTBNQlIyZFMzZTlFVVd5dmN4Z0F5Y3puRUc3bEl5N1RIaW9ZL1h0QStSSjNPTVljCkpKVERoekJFaWtYclhyanJnVjdOazV3YUZ5SkN6QXp1Nk1XYkpIaFZMZVU3Z2d6amtVemZvYm5kNjBXZGJNRWoKRkg2ejBmUEo0MDBZR3FmejJXQlpSZ2VZbzNXbXdZUSt1bXd3V1IzTlFCcFFNTDdFcHM3UXZ3Y2JCZkFTOEM4egpkT0dSR0ZNVyt3NGUzNXVoMDJaUlU2dFB1aGtiSHYvOXNDbHRwRzFRSnZBWFU3R0FadUI2NTZjbDU1N0Z0blVYCmZzVWZsYXE2T2Y1cGxnR1BadFVQTW5uZk9vZEE0L1hOdU92N015ak9vZ0N3Z2piOCtwZ09UMUhIOUdIV25FemoKakJ0T092alV4UWRUb09YaXM4TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQytLZnZVM080TTB3UU0KQUV6MVFPWS9waUlteEJzcHA4MlVlMjF0ZHV0Y2tRN08zcTdYWlhVaWtJNWljOEsxc20vcE1JMDgxdmxOOG1kcQpCTkFMcnlOcFpFVHUrbEViS0U5VW0yT2dQMWcwa0NqRlErRW5tMDNQU1pXY1VVVWxSY0RRaGYxMjZlS01URlp6CkFmMXdCRU1HZS96RmJLRTFHNVBBMFRybXhGd1hqUHUzYW0zY3hUbm8rdUVlU0lCMFl4QUpwWS9LSlFIYmd5RVoKKzlDcjNOQ2dKVWJHTmx5RWtadjd6OHROVFJwTDNYK2xyQ3MvNkZ3d2xRdDRmeFBCMUhDMlc2MXljOHA2b2hXWAphYzV0U0RNUlU4dnJLRldwWXpXcWdkV2VDU3dBWkt6bm0zVWR4TFowNVlGRkxCZGxlV2VaWGIzSXNPdG5lekRkClBCRG5xTkk1QWdNQkFBRUNnZ0VBSVZWNnIzV0t4UFM0WU9Jc20xRWxDME16K1ZlbTYwWmU0d2cveGxCeU1XZTgKRU1jNEhzbktIcVQ0VUltNk45OXZmcERrTVNYOXpZd1FWS1ZEVXNrQWpCam5mSHlrZXY0MTZiN1RWK1BDc25RUwpzWUdVbGp6REJ2TC9Kc2VZTjFCaTNDcWdvNWViL3J2aTY0WU54dlQ0U3NxeEpHcEdWK2pkblk4UHBDUUhnSmtJCnB6bEpROCtXRkZicEptbVBiMGZCSlhNZjVzRm0vVTNhYWlrSVRoSjF5WjUxZUw0KzRxbFJKMForRU9iMTAvdFQKY1ZlN240UGw4cW9FUFJSdTlMN3dESkI5b2VOYnZhQ3Zwb0pydVVNMWtBWmk5VXAra2hkRFJXTThzekNlWGlNWgpqay91WkhNYU12d3BySDlYbkI4VC8xNnZoRUt1Tm03VFpMWUpZYzNHQVFLQmdRRFhzazJhYVdZaTkrdjZLbUYxCm5zOVpteFgxOWhQMi9oWFRKTDRJNHMxYTl3SFp1dWE0QkQ5N2N3QUYrZ2tPRDcvMzNlSWkrUmhjSG8vTG5zeE8KTlQwVUNwekd6SEJVL0pWWk91OXpBclpmWmVXcXJURHY5aFJOb2ltRkZtY3ZNUVRvVEg0ckNkYVNQSWNkUUdwcwpVV1RRRjM5dit5YVk1N0RkempraHhEa3BIUUtCZ1FEaHNsbkkwYWlzbW53UHFKeGsxK21oZFQxNTRDajdOS3c5CnZCMytMYmtXNkNjQy9WS3VkdDRxSmVERUYwRUxvbXNYaXUxbDR2MkVNK1NtWUtMUXdRenFVZUpVRGhwVXF3M2QKdDFuY2xRVzYvdlBFb3V6NHJHZGplTjVVVHdCd0FJdHpvM1hKUkdNZVlUclBnS0l6WVUxSHJQTmRiTjRPTWlFYQpTZnpxVkIrZXpRS0JnSGxnZGJqeG5LOEswamk1UnBTWXBGZnBKSWQvVFNiTlBsek5yVDUwMmxoWTdTcW51Uk5PCkdLY1FSTEFZVHFZaUNNV2pqNUJjbWUra3B3aFBPT3E5bkx3OWFKR2FFNUJQZm45eTRiSFhrZWJIQVdGMUNqZk8KUXdpWXUwS1FJOHB6akM1b2RRc2xBeURSZkxyaU44RHlZSWVVNFhxVFd0bnFieVd4MllaOTFDaWxBb0dBWC9Eago3OVVJSWM5TjI0NHVaVVBQUWQ1SHNzNVNQVzhIcFBxWnVWb1FheWRtcGdPdnFSQklvcHdWYnVYL3RZVm1oc3g4CjNDbmc0Tmo2WXF1RHFyL1YwS25jVHlUcmxvQmNWWnJDYlYwLzRWek5uUkl4TUFpQnJxeEx2b1VTeDRuRHZmV0gKZFhaSHVEdFd0NnlUeHNtZkExQUc1L2tHYi94cFMvYVZ0N3JvOGlVQ2dZQXFwR0ZhdFBML2JpMHN5RklQcUZiUwpTUkd0Z3lMY1I0WFM0UzREUVRJNWFzUlNqR2E5Z1o1azV0VlJpTlpvYUFmMTlVVVI0dUNNMW4xUnV5NldVelh2ClgvZTZueE8yVUFZT1pZQnlnak5CSFNBT0dwNWd6c29FQmh4WER6SjRHRG5RVFZqejdINHB2Smx0bWszWCsxL1IKMTBpTzFWMHlVVW1XcXQzeHJQdjhaQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: null
  name: podinfo-tls-secret
  namespace: podinfo-too
type: kubernetes.io/tls
---
##apiVersion: networking.istio.io/v1beta1
##kind: VirtualService
##metadata:
##  name: podinfo
##  namespace: podinfo
##spec:
##  gateways:
##  - istio-system/public
##  hosts:
##  - podinfo.bigbang.dev
##  http:
##  - route:
##    - destination:
##        host: podinfo
##        port:
##          number: 9898
##---
##apiVersion: networking.istio.io/v1beta1
##kind: VirtualService
##metadata:
##  name: podinfo-too
##  namespace: podinfo-too
##spec:
##  gateways:
##  - istio-system/passthrough
##  hosts:
##  - keycloak.bigbang.dev
##  tls:
##  - match:
##    - sniHosts: ["keycloak.bigbang.dev"]
##    route:
##    - destination:
##        host: podinfo-too
##        port:
##          number: 9899
##---
