name: publish-workflow

on:
  create

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    #if: github.event_name == 'release' && github.event.action == 'published'
    steps:
     - env:
         ACTIONS_RUNNER_DEBUG: true
       run: |
        echo "The publish workflow was triggered!!!!"
