name: publish-workflow

on:
  create:
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        echo "The publish workflow was triggered!!!!"
