on:
  push:
    branches:
      - main

name: release-please-workflow

jobs:
  tag-new-version:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
      release_tag: ${{ steps.release-tag.outputs.tag_name }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: google-github-actions/release-please-action@v3.7.10
        with:
          command: manifest # use configs in release-please-config.json
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> $GITHUB_OUTPUT 
      - id: release-tag
        run: echo "release_tag=${{ steps.tag.outputs.tag_name || false }}" >> $GITHUB_OUTPUT 

  update-release-notes:
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    uses: ./.github/workflows/update-release-info-from-tag.yaml
    with:
      tag-name: ${{ needs.tag-new-version.outputs.release_tag }}
      release-body-top: '\[\/\/\]: # \(MODIFIED BY WORKFLOW\)\\n'
      release-body-bottom: '\\\n### OCI\n\`\`\`console\nzarf package deploy oci://ghcr.io/mxnxpx/packages/zarf-package-podinfos:${{ needs.tag-new-version.outputs.release_tag }}-amd\n\`\`\`'
    secrets: inherit

  publish-release:
    needs: tag-new-version
    runs-on: ubuntu-latest
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    steps:
      - name: Publish Release Artifact
        id: echo-release
        run: echo "RELEASE ARTIFACT WILL BE CREATED AT THIS POINT"