name: update-release-info-from-tag

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'GitHub tag name'
        required: true
      release-body-top:
        description: 'Content to add to the top of the release body'
        required: true
        default: '\[\/\/\]: # \(MODIFIED BY WORKFLOW\)\\n'
        #default: '## DO NOT USE THIS RELEASE\\n'
      release-body-bottom:
        description: 'Content to add to the bottom of the release body'
        required: true
        default: '\\\n\[\/\/\]: # \(MODIFIED BY WORKFLOW\)'
        #default: '\\\n---\n#### HOW TO DEPLOY\n\`\`\`console\nzarf package deploy oci://ghcr.io/something\n\`\`\`'
  workflow_call:
    inputs:
      tag-name:
        required: true
        type: string
      release-body-top:
        type: string
      release-body-bottom:
        type: string

jobs:
  update-release-body:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify Release Body
        id: modify-release-body
        run: |
          TAG_NAME="${{ inputs.tag-name }}"
          ADD_TO_TOP="${{ inputs.release-body-top }}"
          ADD_TO_BOTTOM="${{ inputs.release-body-bottom }}"
          gh release view "v${TAG_NAME}" -R ${{ github.repository }} --json body --jq '.body' > "${TAG_NAME}-release-notes.txt"
          REGEX_CMD_ARGS="-e '1 i\\${ADD_TO_TOP}' -e '\$a ${ADD_TO_BOTTOM}'"
          cat ${TAG_NAME}-release-notes.txt | eval "sed ${REGEX_CMD_ARGS}" > "NEW-${TAG_NAME}-release-notes.txt"
          gh release edit "v${TAG_NAME}" -R ${{ github.repository }} --notes-file "NEW-${TAG_NAME}-release-notes.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
