name: update-release-info-from-tag

#inputs:
#  github-token:
#    description: GitHub token to authenticate to the GitHub REST API
#    required: true
#  tag-name:
#    description: 'GitHub tag name (ex: v0.3.0)'
#    required: true
#
#outputs:
#  latest-package-version:
#    description: Github release ID
#    value: ${{ steps.get-release-id.outputs.release-id }}


on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'GitHub tag name'
        required: true
      release-body-update:
        description: 'Content to append to release body'
        required: true

jobs:
  update-release-body:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Release ID
        id: get-release-id
        run: |
          # Set the input tag name
          TAG_NAME="${{ github.event.inputs.tag-name }}"
          
          # Fetch the releases list using GitHub API
          RELEASES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases")
          
          # Find the release ID for the given tag name
          RELEASE_ID=$(echo "$RELEASES" | jq -r --arg TAG_NAME "$TAG_NAME" '.[] | select(.tag_name == $TAG_NAME) | .id')
          
          echo "Release ID for tag $TAG_NAME: $RELEASE_ID"
          
          echo "::set-output name=release-id::$RELEASE_ID"
        env:
          TAG_NAME: ${{ github.event.inputs.tag-name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Show Release ID
        run: |
          echo "Release ID: ${{ steps.get-release-id.outputs.release-id }}"
      
      - name: Append to Release Body
        id: append-to-release-body
        run: |
          # Set the input release body update
          RELEASE_BODY_UPDATE="${{ github.event.inputs.release-body-update }}"
          
          # Get the current release body using GitHub API
          RELEASE_BODY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.get-release-id.outputs.release-id }}" | jq -r '.body')
          
          # Append the update to the release body
          NEW_RELEASE_BODY="$RELEASE_BODY\n\n$RELEASE_BODY_UPDATE"
          
          # Update the release body using GitHub API
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"body\": \"$NEW_RELEASE_BODY\"}" "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.get-release-id.outputs.release-id }}"
        env:
          RELEASE_BODY_UPDATE: ${{ github.event.inputs.release-body-update }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
