#inputs:
#  github-token:
#    description: GitHub token to authenticate to the GitHub REST API
#    required: true
#  tag-name:
#    description: 'GitHub tag name (ex: v0.3.0)'
#    required: true
#
#outputs:
#  latest-package-version:
#    description: Github release ID
#    value: ${{ steps.get-release-id.outputs.release-id }}

name: update-release-info-from-tag

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'GitHub tag name'
        required: true
      release-body-top:
        description: 'Content to add to the top of the release body'
        default: '\[comment\]: # MODIFIED BY WORKFLOW\\n'
      release-body-bottom:
        description: 'Content to add to the bottom of the release body'
        default: '\\\n### OCI\n\`\`\`console\nzarf package deploy oci://ghcr.io/something\n\`\`\`'

jobs:
  update-release-body:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify Release Body
        id: modify-release-body
        run: |
          TAG_NAME="${{ github.event.inputs.tag-name }}"
          ADD_TO_TOP="${{ github.event.inputs.release-body-top }}"
          ADD_TO_BOTTOM="${{ github.event.inputs.release-body-bottom }}"
          gh release view "v${TAG_NAME}" -R ${{ github.repository }} --json body --jq '.body' > "${TAG_NAME}-release-notes.txt"
          REGEX_CMD_ARGS="-e '1 i\\${ADD_TO_TOP}' -e '\$a ${ADD_TO_BOTTOM}'"
          cat ${TAG_NAME}-release-notes.txt | eval "sed ${REGEX_CMD_ARGS}" > "NEW-${TAG_NAME}-release-notes.txt"
          gh release edit "v${TAG_NAME}" -R ${{ github.repository }} --notes-file "NEW-${TAG_NAME}-release-notes.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
