#inputs:
#  github-token:
#    description: GitHub token to authenticate to the GitHub REST API
#    required: true
#  tag-name:
#    description: 'GitHub tag name (ex: v0.3.0)'
#    required: true
#
#outputs:
#  latest-package-version:
#    description: Github release ID
#    value: ${{ steps.get-release-id.outputs.release-id }}

name: update-release-info-from-tag

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'GitHub tag name'
        required: true
      release-body-update:
        description: 'Content to append to release body'
        required: true

jobs:
  update-release-body:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Append to Release Body
        id: append-to-release-body
        run: |
          TAG_NAME="${{ github.event.inputs.tag-name }}"
          RELEASE_BODY=$(gh release view "v${TAG_NAME}" -R ${{ github.repository }} --json body --jq '.body')
          RELEASE_BODY_UPDATE="${{ github.event.inputs.release-body-update }}"
          NEW_RELEASE_BODY="${RELEASE_BODY}\n${RELEASE_BODY_UPDATE}"
          gh release edit "v${TAG_NAME}" -R ${{ github.repository }} --notes "${NEW_RELEASE_BODY}"
        env:
          RELEASE_BODY_UPDATE: ${{ github.event.inputs.release-body-update }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
